# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fronttestevaga

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://neogenessdigital.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0017949d9413446b983b81071a3d4018 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_731c856146ce414590f1f054ddb3e646 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: neogenessdigital.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0017949d9413446b983b81071a3d4018 }}/testefrontvaga:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fronttestevaga'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6ebed5fdcfd542739a5619992e94eab0 }}
        images: 'neogenessdigital.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0017949d9413446b983b81071a3d4018 }}/testefrontvaga:${{ github.sha }}'